# SPDX-FileCopyrightText: 2026 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
esphome:
  name: cmsis-dap-wrapper-test
  friendly_name: CMSIS DAP Wrapper Test

substitutions:
  purpose_nice: CMSIS DAP Wrapper Test

external_components:
  - source:
      type: local
      path: ../components
    components: [cmsis_dap_tcp]

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

cmsis_dap_tcp:
  - id: cmsis_dap_primary
    tck_pin: GPIO18
    tms_pin: GPIO5
    tdi_pin: GPIO23
    tdo_pin: GPIO34
    led_pin: GPIO32
    led_active_high: false
    port: 4441
    service_name: ULX3S JTAG
    io_port_write_cycles: 72
    delay_slow_cycles: 5
    uart_bridge:
      tx_pin: GPIO3
      rx_pin: GPIO1
      port: 4442
      uart_num: 1
      baud_rate: 115200
      data_bits: 8
      parity: NONE
      stop_bits: 1

  - id: cmsis_dap_secondary
    tck_pin: GPIO19
    tms_pin: GPIO21
    tdi_pin: GPIO22
    tdo_pin: GPIO25
    ntrst_pin: GPIO26
    nreset_pin: GPIO27
    led_pin: GPIO33
    led_active_high: true
    port: 4443
    service_name: Other ULX3S JTAG
    io_port_write_cycles: 72
    delay_slow_cycles: 5
    uart_bridge:
      tx_pin: GPIO15
      rx_pin: GPIO14
      port: 4444
      uart_num: 2
      baud_rate: 115200
      data_bits: 8
      parity: NONE
      stop_bits: 1

safe_mode:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  - platform: esphome
    password: !secret ota_password2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password2
  power_save_mode: none
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "abc Fallback Hotspot"
    password: !secret wifi_password2

captive_portal:
# To have a "next url" for improv serial
web_server:
